const { useEffect, useRef, useState } = window.wp.element;
import {
    Box, 
    Button, 
    FormControl, 
    InputLabel, 
    MenuItem, 
    Select, 
    CircularProgress,
    FormControlLabel,
    Checkbox,
    LinearProgress,
    RadioGroup,
    Radio,
    Typography
} from "@mui/material";
import Grid from '@mui/material/Grid';
import axios from 'axios';
import { marked } from "marked";
import { buttonActionTypes } from "../Helpers";
import { ApplyContentToEditor } from "../BlockEditorHelpers";
import { useSnackbar } from "../SnackbarContext";
import { Loading } from "./Loading";
import InputMultiline from "./Input";
import { CustomTheme } from "../theme-config";

const DataDisplay = ({
     data,
     contentLang,
     handleContentLangChange,
     contentTone,
     handleContentToneChange,
     contentType,
     handleContentTypeChange,
     imageStyle,
     handleImageStyleChange,
     imageSize,
     handleImageSizeChange,
     speechVoice,
     handleSpeechVoiceChange,
     isOpen,
     onClose,
     selectedBlock,
     options,
     setDismissableModal
}) => {
    const { showSnackbar } = useSnackbar();

    const [loading, setLoading] = useState(false);
    const [content, setContent] = useState(false);
    const [disabledContentType, setDisabledContentType] = useState(false);
    const [subject, setSubject] = useState('');

    const [imagePreview, setImagePreview] = useState(null);
    const [showImageSelector, setShowImageSelector] = useState(false);

    const [progress, setProgress] = useState(0);
    const [showProgress, setShowProgress] = useState(false);

    const MAX_TTS_LENGTH = 1000;

    // Speech is generated by an external queue and regularly takes over a
    // minute, so polling needs an explicit ceiling instead of running until the
    // user closes the tab.
    const POLL_INTERVAL_MS = 3000;
    const POLL_TIMEOUT_MS = 5 * 60 * 1000;

    // Held in refs so the timers survive re-renders and can still be stopped
    // when the modal unmounts mid-generation.
    const pollTimers = useRef({ poll: null, progress: null, timeout: null });

    const stopPolling = () => {
        const { poll, progress, timeout } = pollTimers.current;
        if (poll) clearInterval(poll);
        if (progress) clearInterval(progress);
        if (timeout) clearTimeout(timeout);
        pollTimers.current = { poll: null, progress: null, timeout: null };
    };

    useEffect(() => stopPolling, []);

    const getButtonAction = () => options.action || null;

    const isDiabledContentType = () => {
        let buttonAction = getButtonAction();
        let checkes = ['comment', 'thumbnail', 'title', 'gallery', 'medias'];
        if(buttonAction && checkes.some(check => (buttonAction.toLowerCase()).includes(check))){
            return true;
        }

        return false;
    }

    useEffect(() => {
        let subject = '';
        let editorContent = '';

        const textBlocks = ["core/paragraph", "core/heading", "core/quote", "core/list"];
            
        if (selectedBlock && selectedBlock?.name && textBlocks.includes(selectedBlock.name)) {
            const blockContent = selectedBlock.attributes.content;
            
            if (blockContent) {
                subject = blockContent.trim();
            }
        } else {
            const gutenbergTitle = document.querySelector('.editor-post-title__input');
            if (gutenbergTitle) {
                subject = gutenbergTitle.textContent.trim();
            } else {
                const classicTitle = document.getElementById('title');
                if (classicTitle) {
                    subject = classicTitle.value;
                }
            }
        }

        if(getButtonAction() == buttonActionTypes.postSeoKeyword){
            const blocks = wp.data.select('core/block-editor').getBlocks();
            if (blocks && blocks.length) {
                const textContent = blocks
                    .filter(block => textBlocks.includes(block.name))
                    .map(block => block.attributes.content || '')
                    .join(' ')
                    .trim();
                
                if (textContent) {
                    editorContent += textContent;
                }
            } else {
                const classicContent = document.getElementById('content');
                if (classicContent) {
                    editorContent += classicContent.value.trim();
                }
            }

            subject += subject ? "\n" + editorContent : editorContent;
        }

        if(subject){
            setSubject(subject);
        }

        setDisabledContentType(isDiabledContentType());
    });

    const openMediaUploader = () => {
        const frame = wp.media({
            title: hai_data.texts.select_image,
            library: { type: "image" },
            multiple: false,
            button: { text: hai_data.texts.select_image }
        });

        frame.on("select", function () {
            const attachment = frame.state().get("selection").first().toJSON();
            setImagePreview(attachment.url);
        });

        frame.open();
    };

    const handleCheckProductGenerator = (e) => {
        setShowImageSelector(e.target.checked);
    };

    const handleSubmit = async (event) => {
        event.preventDefault();

        const form = event.target;
        if (!form.checkValidity()) {
            form.reportValidity();
            return;
        }

        if(contentType === 'text-to-speech' && subject?.length > MAX_TTS_LENGTH){
            showSnackbar(hai_data.texts.text_to_speech_is_over, 'error');
            return;
        }

        setLoading(true);
        setContent(null);
    
        const formData = new FormData(event.target);
        const queryString = new URLSearchParams(formData).toString();
        const baseData = `action=hai_generate_content&nonce=${hai_data.nonce}&${queryString}&buttonAction=${options.action || null}&type=${contentType}`;

        const makeRequest = async (url, data) => {
            try {
                const response = await axios.post(url, data, {
                    headers: {
                        'Content-Type': 'application/x-www-form-urlencoded',
                        'Accept': 'application/json',
                    },
                });

                return response;
            } catch (error) {
                showSnackbar(hai_data.texts.generate_error, 'error');
                console.error(error);
                throw error;
            }
        };
    
        const afterGenerate = (response, data) => {
            stopPolling();
            setContent(data);
            useGeneratedContent({ data, id: response?.data?.data?.id });
            showSnackbar(hai_data.texts.generate_success, 'success');
            setLoading(false);
            setProgress(100);
            setShowProgress(false);
            setDismissableModal(true);
        };

        const failGeneration = (message) => {
            stopPolling();
            showSnackbar(message || hai_data.texts.generate_error, 'error');
            setLoading(false);
            setProgress(0);
            setShowProgress(false);
            setDismissableModal(true);
        };

        // Image and speech are queued on different endpoints; polling the image
        // one for a speech job would never resolve.
        const statusAction = contentType === 'text-to-speech'
            ? 'hai_check_audio_status'
            : 'hai_check_image_status';

        const startPolling = (contentId) => {
            if (!contentId) {
                failGeneration(hai_data.texts.generate_error);
                return;
            }

            setProgress(0);
            setShowProgress(true);

            // Speech can take a couple of minutes, so the user keeps the
            // ability to close and walk away. Closing unmounts this component
            // and the cleanup above stops the timers; the job still finishes
            // server side and the result stays in their account.
            setDismissableModal(true);

            pollTimers.current.progress = setInterval(() => {
                setProgress((prev) => (prev >= 90 ? prev : prev + 1));
            }, POLL_INTERVAL_MS);

            pollTimers.current.timeout = setTimeout(() => {
                failGeneration(hai_data.texts.generate_timeout);
            }, POLL_TIMEOUT_MS);

            const checkOnce = async () => {
                let checkResponse;

                try {
                    checkResponse = await axios.post(
                        hai_data.ajax_url,
                        `action=${statusAction}&nonce=${hai_data.nonce}&content_id=${contentId}`,
                        {
                            headers: {
                                'Content-Type': 'application/x-www-form-urlencoded',
                                'Accept': 'application/json',
                            },
                        }
                    );
                } catch (error) {
                    // A single dropped poll is not fatal; the timeout above is
                    // what ends a job that never comes back.
                    console.error(error);
                    return;
                }

                if (!checkResponse?.data?.success) {
                    failGeneration(hai_data.texts.generate_error);
                    return;
                }

                const checkStatus = checkResponse?.data?.data?.status || null;
                const checkData = checkResponse?.data?.data?.content || null;

                if (checkStatus === 'done' && checkData) {
                    afterGenerate(checkResponse, checkData);
                    return;
                }

                // The server drops the placeholder when a job fails, so
                // anything that is not queued or done means it will not arrive.
                if (checkStatus && !['queued', 'processing', 'pending'].includes(checkStatus)) {
                    failGeneration(hai_data.texts.generate_error);
                }
            };

            pollTimers.current.poll = setInterval(checkOnce, POLL_INTERVAL_MS);

            // A short job can already be finished by the time the queue replies,
            // and waiting a full interval to discover that makes a fast result
            // feel slow. The interval is assigned first so a result here can
            // clear it.
            checkOnce();
        };

        try {
            setDismissableModal(false);

            const response = await makeRequest(hai_data.ajax_url, baseData);

            if (!response.data.success) {
                setDismissableModal(true);
                throw new Error("Request failed.");
            }

            const data = response?.data?.data?.content || null;
            const status = response?.data?.data?.status || null;

            if (response?.data?.data?.msg) {
                showSnackbar(response.data.data.msg, response.data.data.status);
            }

            if (status === 'done' && data) {
                afterGenerate(response, data);
                return;
            }

            // A queued job carries no content yet, only an id to poll. The old
            // check required content to be present before it would poll, so a
            // queued response left the modal spinning with nothing running.
            if (status && status !== 'done') {
                startPolling(response?.data?.data?.content_id);
                return;
            }

            failGeneration(hai_data.texts.generate_error);
        } catch (error) {
            console.error(error);
            stopPolling();
            setLoading(false);
            setShowProgress(false);
            setDismissableModal(true);
        }
    };

    const useGeneratedContent = ({ data = null, id = null }) => {
        let stringData = data ? data : content;

        if (stringData) {
            if (contentType == 'text') {
                const htmlContent = marked(stringData);

                ApplyContentToEditor({
                    content: htmlContent, 
                    type: 'html', 
                    block: selectedBlock, 
                    options: {id: id, buttonAction: (options.action || null)}
                });
            } else if (contentType == 'image') {
                ApplyContentToEditor({
                    content: stringData, 
                    type: 'image', 
                    block: selectedBlock, 
                    options: {id: id, buttonAction: (options.action || null)}
                });
            } else if (contentType == 'text-to-speech') {
                ApplyContentToEditor({
                    content: stringData, 
                    type: 'text-to-speech', 
                    block: selectedBlock, 
                    options: {id: id, buttonAction: (options.action || null)}
                });
            }

            onClose();
        }
    }

    const handleChangeSubject = (e) => {
        const value = e.target.value;
        if (contentType === 'text-to-speech' && value?.length > MAX_TTS_LENGTH) return;
        setSubject(value);
    }

    const generatorTypes = hai_data.generator.types ? Object.entries(hai_data.generator.types) : {};
    const contentTones = hai_data.generator.contentTones ? Object.entries(hai_data.generator.contentTones) : {};
    const imageStyles = hai_data.generator.imageStyles ? Object.entries(hai_data.generator.imageStyles) : {};
    const productImageStyles = hai_data.generator.productImageStyles ? Object.entries(hai_data.generator.productImageStyles) : {};
    const imageSizes = hai_data.generator.imageSizes ? Object.entries(hai_data.generator.imageSizes) : {};
    const languages = hai_data.generator.languages ? Object.entries(hai_data.generator.languages) : {};
    const speechVoices = hai_data.generator.speechVoices ? Object.entries(hai_data.generator.speechVoices) : {};

    return (
        <Box sx={{
            width: '100%',
            p: 2,
        }}>
            <Box>
                {!loading ? (
                    <form method="post" onSubmit={handleSubmit}>
                        <FormControl component="fieldset" sx={{ width: '100%', mb: 2 }} required>
                            <RadioGroup
                                name="type"
                                value={contentType}
                                onChange={handleContentTypeChange}
                            >
                                <Grid container spacing={2}>
                                {generatorTypes.map(([key, { title, icon }]) => (
                                    <Grid item xs={4} sm={4} md={4} key={key}>
                                        <FormControlLabel
                                            value={key}
                                            control={<Radio sx={{ display: 'none' }} />}
                                            disabled={disabledContentType}
                                            sx={{
                                                width: '100%',
                                                alignItems: 'stretch',                                             
                                                '& .MuiFormControlLabel-label': {
                                                  width: '100%',
                                                },
                                            }}
                                            label={
                                                <Box
                                                    sx={{
                                                        width: '100%', 
                                                        display: 'block',
                                                        cursor: 'pointer',
                                                        borderRadius: 2,
                                                        p: 2,
                                                        border: '2px solid',
                                                        borderColor: contentType === key ? '#00bcd4' : '#282828',
                                                        color: '#fff',
                                                        textAlign: 'center',
                                                        transition: 'all 0.2s',
                                                        '&:hover': {
                                                            borderColor: '#00bcd4',
                                                        },
                                                        ...(disabledContentType && contentType !== key && {
                                                            opacity: '0.3',
                                                            pointerEvents: 'none',
                                                        }),
                                                    }}
                                                    >
                                                    <Box
                                                        sx={{ display: 'flex', justifyContent: 'center', mb: 1 }}
                                                        dangerouslySetInnerHTML={{ __html: icon }}
                                                    />
                                                    <Typography variant="body1" fontWeight="500">
                                                        {title}
                                                    </Typography>
                                                </Box>
                                            }
                                            />
                                    </Grid>
                                ))}
                                </Grid>
                            </RadioGroup>
                        </FormControl>

                        {contentType === "image" && showImageSelector && (
                            <Box
                                sx={{
                                    border: "2px dashed #ccc",
                                    borderRadius: "10px",
                                    p: 2,
                                    textAlign: "center",
                                    cursor: "pointer",
                                    mb: 2,
                                    color: CustomTheme.palette.text.primary
                                }}
                                onClick={openMediaUploader}
                            >
                                <input
                                    type="hidden"
                                    name="original_image"
                                    value={imagePreview}
                                    required
                                />
                                {imagePreview ? (
                                    <>
                                        <img
                                            src={imagePreview}
                                            style={{ width: '100%', maxHeight: '150px', objectFit: 'contain' }}
                                        />
                                    </>
                                ) : (
                                    hai_data.texts.click_select_image
                                )}
                            </Box>
                        )}

                        {(!showImageSelector || contentType === "text-to-speech") && (
                            <div style={{marginBottom: '10px'}}>
                                <InputMultiline
                                    name="subject" 
                                    defaultValue={subject}
                                    onChange={handleChangeSubject}
                                    required
                                    sx={{ minHeight: '170px' }}
                                    maxLength={contentType === 'text-to-speech' ? MAX_TTS_LENGTH : undefined}
                                    />

                                 {contentType === 'text-to-speech' && (
                                    <div style={{ fontSize: '12px', color: '#939393', marginTop: '4px' }}>
                                        {subject?.length} {hai_data.texts.from} {MAX_TTS_LENGTH} {hai_data.texts.characters}
                                    </div>
                                )}
                            </div>
                        )}

                        {contentType === "text-to-speech" && (
                            <FormControl fullWidth variant="outlined" sx={{mb: 2}}>
                                <InputLabel sx={{color: CustomTheme.palette.text.primary}}>
                                    { hai_data.texts.voices }
                                </InputLabel>
                                <Select
                                    defaultValue={hai_data.generator.defaults.speech_voice}
                                    onChange={handleSpeechVoiceChange}
                                    color="primary"
                                    sx={{color: CustomTheme.palette.text.primary}}
                                    name="voice"
                                    required
                                >
                                    {speechVoices?.map(([key, label]) => (
                                        <MenuItem key={key} value={key}>
                                            {label}
                                        </MenuItem>
                                    ))}
                                </Select>
                            </FormControl>
                        )}

                        {contentType === "image" && (
                            <Box sx={{ mb: 2 }}>
                                <FormControlLabel
                                    className="MuiFormControlLabel-CheckboxLabel"
                                    control={
                                        <Checkbox
                                            checked={showImageSelector}
                                            onChange={(e) => handleCheckProductGenerator(e)}
                                        />
                                    }
                                    label={hai_data.texts.generate_product_image}
                                />
                            </Box>
                        )}

                        {contentType === 'image' ? (
                            <>
                                <FormControl fullWidth variant="outlined" sx={{ mb: 2 }}>
                                    <InputLabel sx={{ color: CustomTheme.palette.text.primary }}>
                                        {hai_data.texts.style}
                                    </InputLabel>
                                    <Select
                                        value={showImageSelector ? hai_data.generator.defaults.product_image_style : imageStyle}
                                        onChange={handleImageStyleChange}
                                        color="primary"
                                        sx={{ color: CustomTheme.palette.text.primary }}
                                        name="style"
                                        required
                                    >
                                        {(showImageSelector ? productImageStyles : imageStyles)?.map(([key, label]) => (
                                            <MenuItem key={key} value={key}>
                                                {label}
                                            </MenuItem>
                                        ))}
                                    </Select>
                                </FormControl>
                                
                                {!showImageSelector && (
                                    <FormControl fullWidth variant="outlined" sx={{ mb: 2 }}>
                                        <InputLabel>{hai_data.texts.size}</InputLabel>
                                        <Select
                                            value={imageSize}
                                            onChange={handleImageSizeChange}
                                            color="primary"
                                            sx={{ color: CustomTheme.palette.text.primary }}
                                            name="size"
                                            required
                                        >
                                            {imageSizes?.map(([key, label]) => (
                                                <MenuItem key={key} value={key}>
                                                    {label}
                                                </MenuItem>
                                            ))}
                                        </Select>
                                    </FormControl>
                                )}
                            </>
                        ) : (
                            <>
                                {contentType === "text" ? (
                                    <>
                                        <FormControl fullWidth variant="outlined" sx={{ mb: 2 }}>
                                            <InputLabel>{hai_data.texts.language}</InputLabel>
                                            <Select
                                                value={contentLang}
                                                onChange={handleContentLangChange}
                                                color="primary"
                                                sx={{ color: CustomTheme.palette.text.primary }}
                                                name="lang"
                                                required
                                            >
                                                {languages?.map(([code, label]) => (
                                                    <MenuItem key={code} value={code}>
                                                        {typeof label === "string" ? label : code}
                                                    </MenuItem>
                                                ))}
                                            </Select>
                                        </FormControl>

                                        <FormControl fullWidth variant="outlined" sx={{ mb: 2 }}>
                                            <InputLabel>{hai_data.texts.tone}</InputLabel>
                                            <Select
                                                value={contentTone}
                                                onChange={handleContentToneChange}
                                                color="primary"
                                                sx={{ color: CustomTheme.palette.text.primary }}
                                                name="tone"
                                                required
                                            >
                                                {contentTones?.map(([key, label]) => (
                                                    <MenuItem key={key} value={key}>
                                                        {label}
                                                    </MenuItem>
                                                ))}
                                            </Select>
                                        </FormControl>
                                    </>
                                ) : null}
                            </>
                        )}

                        {showProgress && (
                            <Box sx={{ width: '100%', my: 2 }}>
                                <LinearProgress variant="determinate" value={progress} />
                            </Box>
                        )}

                        <Button
                            type="submit"
                            variant="contained"
                            color="primary"
                            disabled={loading}
                            startIcon={loading ? <CircularProgress size={17} /> : null}
                        >
                            {loading ? hai_data.texts.doing : hai_data.texts.generate}
                        </Button>
                    </form>
                ) : (
                    <Loading />
                )}
            </Box>
        </Box>
    );
}

export default DataDisplay;