<?php
namespace HooshinaAi\App\Generator;

use HooshinaAi\App\Helper;
use HooshinaAi\App\Provider\HaiClient;
use HooshinaAi\App\Uploader;

class ImageGenerator extends GeneratorAbstract implements GeneratorInterface
{
    public function generate()
    {
        $client = new HaiClient();

        $params = [
            'subject' => $this->get_param('subject'),
            'size' => $this->get_param('size', '1024x1024'),
            'style' => $this->get_param('style', 'classical-realism'),
            'locale' => Helper::get_locale(),
        ];

        $imageUrl = $this->get_param('original_image');

        $route = Generator::TextToImage;

        if(!empty($imageUrl) && filter_var($imageUrl, FILTER_VALIDATE_URL)){
            $params['original_image'] = $imageUrl;
            $route = Generator::ProductImage;
            unset($params['subject']);
        }

        $params['model'] = $route;

        $response = $client->client('generator/image/queue/' . $route, $params);

        $url = $response ? $this->find($response, 'output') : null;
        $status = $response ? $this->find($response, 'status') : 'done';
        $contentId = $response ? $this->find($response, 'content_id') : null;

        if($status == 'done' && filter_var($url, FILTER_VALIDATE_URL)){
            $uploadData = $this->uploadFile($url);
        }

        return [
            'content' => ($uploadData['url'] ?? $url),
            'id' => ($uploadData['id'] ?? null), 
            'status' => $status,
            'content_id' => $contentId
        ];
    }

    public function get_image_styles($model = null)
    {
        $client = new HaiClient(['method' => 'get']);
        $response = $client->client('generator/image/styles', ['model' => $model]);

        return $response ? $this->find($response, 'data') : null;
    }

    public function get_image_sizes()
    {
        $client = new HaiClient(['method' => 'get']);
        $response = $client->client('generator/image/sizes');

        return $response ? $this->find($response, 'data') : null;
    }

    /**
     * Polls one queued image job.
     *
     * Images are generated by an external queue now, so this is called
     * repeatedly until there is a result rather than once as a formality.
     */
    public function get_image_status($content_id = null)
    {
        if(empty($content_id)){
            return ['content' => null, 'id' => null, 'status' => 'failed'];
        }

        $client = new HaiClient(['method' => 'get']);
        $response = $client->client('generator/image/status', ['content_id' => $content_id]);

        // HaiClient returns the Throwable itself on failure, and an object is
        // never empty(), so a truthiness check would let an error through to
        // find(), which walks the exception's stack trace and can lift an
        // unrelated 'status' or 'media_url' out of the frame arguments and
        // report a failed poll as a finished one.
        if(!is_array($response)){
            return ['content' => null, 'id' => null, 'status' => 'failed'];
        }

        $url = $this->find($response, 'media_url');
        $status = $this->find($response, 'status');

        if(empty($status)){
            return ['content' => null, 'id' => null, 'status' => 'failed'];
        }

        if(filter_var($url, FILTER_VALIDATE_URL) && $status == 'done'){
            $uploadData = $this->uploadFile($url);
        }

        return ['content' => $url, 'id' => $uploadData['id'] ?? null, 'status' => $status];
    }
}